[book]
authors = ["Saket Sinha"]
language = "en"
multilingual = false
src = "src"
title = "German Book"

[output.html]
curly-quotes = true
git-repository-url = "https://github.com/disdi/germanbook"
site-url = "https://saketsinha.de/germanbook/"

[output.html.fold]
enable = true
level = 0

[output.html.playground]
editable = true
