[book]
authors = ["Glyn Normington"]
language = "en"
multilingual = false
src = "src"
title = "Little Book"

[output.html]
curly-quotes = true
git-repository-url = "https://github.com/maverickcasanova/book"
site-url = "https://maverickcasanova.github.io/book/"
